openapi: 3.0.0

info:
  title: GigaChill Test Utils API
  version: 0.1.0
  description: >
    Спецификация вспомогательных эндпоинтов, 
    доступных только в тестовом окружении (profile=test).

tags:
  - name: Database

paths:
  /test-utils/cleanup:
    post:
      tags:
        - Database
      summary: Очистить базу данных
      description: |
        Полная очистка всех таблиц — только для тестового профиля (profile=test).
      responses:
        "204":
          description: No Content
